const countryTimezones: Record<string, string> = {
  'United States': 'GMT-5',
  'Canada': 'GMT-5',
  'United Kingdom': 'GMT+0',
  'Germany': 'GMT+1',
  'France': 'GMT+1',
  'Spain': 'GMT+1',
  'Italy': 'GMT+1',
  'Netherlands': 'GMT+1',
  'Belgium': 'GMT+1',
  'Switzerland': 'GMT+1',
  'Austria': 'GMT+1',
  'Sweden': 'GMT+1',
  'Norway': 'GMT+1',
  'Denmark': 'GMT+1',
  'Finland': 'GMT+2',
  'Poland': 'GMT+1',
  'Czech Republic': 'GMT+1',
  'Greece': 'GMT+2',
  'Portugal': 'GMT+0',
  'Ireland': 'GMT+0',
  'Australia': 'GMT+10',
  'New Zealand': 'GMT+12',
  'Japan': 'GMT+9',
  'China': 'GMT+8',
  'India': 'GMT+5:30',
  'Singapore': 'GMT+8',
  'Hong Kong': 'GMT+8',
  'South Korea': 'GMT+9',
  'Thailand': 'GMT+7',
  'Malaysia': 'GMT+8',
  'Indonesia': 'GMT+7',
  'Philippines': 'GMT+8',
  'Vietnam': 'GMT+7',
  'UAE': 'GMT+4',
  'Saudi Arabia': 'GMT+3',
  'Israel': 'GMT+2',
  'Turkey': 'GMT+3',
  'Russia': 'GMT+3',
  'Brazil': 'GMT-3',
  'Mexico': 'GMT-6',
  'Argentina': 'GMT-3',
  'Chile': 'GMT-3',
  'Colombia': 'GMT-5',
  'Peru': 'GMT-5',
  'South Africa': 'GMT+2',
  'Egypt': 'GMT+2',
  'Kenya': 'GMT+3',
  'Nigeria': 'GMT+1',
};

export const COUNTRIES = Object.keys(countryTimezones);

export const TIMEZONES = [
  { value: 'GMT-12', label: 'GMT-12' },
  { value: 'GMT-11', label: 'GMT-11' },
  { value: 'GMT-10', label: 'GMT-10' },
  { value: 'GMT-9', label: 'GMT-9' },
  { value: 'GMT-8', label: 'GMT-8' },
  { value: 'GMT-7', label: 'GMT-7' },
  { value: 'GMT-6', label: 'GMT-6' },
  { value: 'GMT-5', label: 'GMT-5' },
  { value: 'GMT-4', label: 'GMT-4' },
  { value: 'GMT-3', label: 'GMT-3' },
  { value: 'GMT-2', label: 'GMT-2' },
  { value: 'GMT-1', label: 'GMT-1' },
  { value: 'GMT+0', label: 'GMT+0' },
  { value: 'GMT+1', label: 'GMT+1' },
  { value: 'GMT+2', label: 'GMT+2' },
  { value: 'GMT+3', label: 'GMT+3' },
  { value: 'GMT+4', label: 'GMT+4' },
  { value: 'GMT+5', label: 'GMT+5' },
  { value: 'GMT+5:30', label: 'GMT+5:30' },
  { value: 'GMT+6', label: 'GMT+6' },
  { value: 'GMT+7', label: 'GMT+7' },
  { value: 'GMT+8', label: 'GMT+8' },
  { value: 'GMT+9', label: 'GMT+9' },
  { value: 'GMT+10', label: 'GMT+10' },
  { value: 'GMT+11', label: 'GMT+11' },
  { value: 'GMT+12', label: 'GMT+12' },
  { value: 'GMT+13', label: 'GMT+13' },
];

export function getTimezoneForCountry(country?: string): string | undefined {
  if (!country) return undefined;
  return countryTimezones[country];
}
